- build.gradle
> ecr 배포 에러 수정

- src/main/java/com/puppy/pawpaw_project_be/application/auth/command/CustomOAuth2UserService.java
> oauth2 에러 수정

- src/main/java/com/puppy/pawpaw_project_be/application/auth/command/CustomOAuth2UserService.java
- src/main/java/com/puppy/pawpaw_project_be/application/auth/command/SignService.java
- src/main/java/com/puppy/pawpaw_project_be/application/auth/query/AuthQuery.java
- src/main/java/com/puppy/pawpaw_project_be/config/CustomUserDetailService.java
- src/main/java/com/puppy/pawpaw_project_be/config/auth/filter/JwtFilter.java
- src/main/java/com/puppy/pawpaw_project_be/controller/auth/AuthController.java
- src/main/java/com/puppy/pawpaw_project_be/domain/auth/domain/OAuth2CustomUser.java
Fix: 버그 수정 - JWT 토큰 관련
Feat: 유저 정보 조회 API 추가
> Fix: 버그 수정 - JWT 토큰 관련, Feat: 유저 정보 조회 API 추가

- src/main/java/com/puppy/pawpaw_project_be/config/annotation/AuthenticatedUserId.java
- src/main/java/com/puppy/pawpaw_project_be/controller/auth/AuthController.java
- src/main/java/com/puppy/pawpaw_project_be/exception/common/BusinessException.java
- src/main/java/com/puppy/pawpaw_project_be/exception/common/ErrorCode.java
- src/main/java/com/puppy/pawpaw_project_be/exception/common/GlobalExceptionHandler.java
Auth 컨트롤러가 사용하는 서비스 메소드에서 발생할 수 있는 Exception 에 대해 Swagger ApiResponses에 표기 수정
> Fix: Auth controller ApiResponse 수정

- src/main/java/com/puppy/pawpaw_project_be/domain/board/controller/BoardRestController.java
- src/main/java/com/puppy/pawpaw_project_be/domain/board/dto/BoardDto.java
- src/main/java/com/puppy/pawpaw_project_be/domain/board/entity/Board.java
- src/main/java/com/puppy/pawpaw_project_be/domain/board/repository/BoardRepository.java
- src/main/java/com/puppy/pawpaw_project_be/domain/board/service/BoardService.java
- src/main/java/com/puppy/pawpaw_project_be/global/response/BaseResponse.java
커뮤니티의 핵심 기능인 게시글의 등록, 수정, 삭제 기능의 추가
> [feat]JWT 토큰을 파싱하여 UserId를 얻고, 게시글을 등록, 수정, 삭제하는 기능을 구현한다.

- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
> Fix: error Code 중복 수정

- api/src/main/java/kr/co/pawpaw/api/application/board/BoardLikeService.java
- api/src/main/java/kr/co/pawpaw/api/controller/board/BoardLikeRestController.java
- common/src/main/java/kr/co/pawpaw/common/exception/board/BoardLikeException.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/domain/BoardLikes.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/repository/BoardLikesRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/service/command/BoardLikeCommand.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/service/query/BoardLikeQuery.java
1. 좋아요 예외코드 및 예외처리 코드 추가
2.  좋아요 추가,삭제 기능을 분리
3.  BoardLikeController에 swagger 코드 추가
4.  JpaRepository에 직접 의존하는 코드를 수정
> 좋아요 기능과 관련된 전반적인 코드를 수정한다.

- api/src/main/java/kr/co/pawpaw/api/ApiApplication.java
- api/src/main/java/kr/co/pawpaw/api/application/auth/SignUpService.java
- api/src/main/java/kr/co/pawpaw/api/config/SecurityConfig.java
- api/src/main/java/kr/co/pawpaw/api/controller/auth/AuthController.java
- api/src/main/java/kr/co/pawpaw/api/dto/auth/DuplicateEmailResponse.java
- api/src/main/java/kr/co/pawpaw/api/dto/auth/SignUpRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/auth/SocialSignUpRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/position/PositionRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/position/PositionResponse.java
- api/src/main/java/kr/co/pawpaw/api/dto/user/UserResponse.java
- api/src/main/resources/application-cookie.yml
- api/src/test/java/kr/co/pawpaw/api/application/auth/SignUpServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/auth/SignUpRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/auth/SocialSignUpRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/user/UserResponseTest.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/position/Position.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/term/repository/TermCustomRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/user/domain/User.java
- domain/domain-redis/src/main/resources/application-verification.yml
Feat: 회원가입 이메일 중복 확인
Feat: 회원가입 장소 필드 위도 경도 추가
> Feat: 회원가입 이메일 중복 확인 Feat: 회원가입 장소 필드 위도 경도 추가

- api/src/main/java/kr/co/pawpaw/api/application/sms/SmsService.java
- api/src/main/java/kr/co/pawpaw/api/application/term/TermService.java
- api/src/main/java/kr/co/pawpaw/api/config/property/JwtProperties.java
- api/src/main/java/kr/co/pawpaw/api/config/property/OAuth2Properties.java
- api/src/main/java/kr/co/pawpaw/api/config/property/VerificationProperties.java
- api/src/main/java/kr/co/pawpaw/api/dto/sms/CheckVerificationCodeResponse.java
- api/src/main/resources/application-sms.yml
- api/src/main/resources/application.yml
- api/src/test/java/kr/co/pawpaw/api/application/auth/SignUpServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/application/file/FileServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/application/sms/SmsServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/application/term/TermServiceTest.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
- common/src/main/java/kr/co/pawpaw/common/exception/sms/OutOfSmsLimitException.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/sms/domain/SmsUsagePurpose.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/sms/repository/SmsLogRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/sms/service/query/SmsLogQuery.java
- domain/domain-rdb/src/test/java/kr/co/pawpaw/domainrdb/sms/service/query/SmsLogQueryTest.java
- domain/domain-redis/src/test/java/kr/co/pawpaw/domainredis/auth/service/query/OAuth2TempAttributesQueryTest.java
Feat: Sms 인증번호 일당 전송 횟수(3회) 제한 추가
> Feat: Sms 인증번호 일당 전송 횟수 제한 추가

- api/src/main/java/kr/co/pawpaw/api/application/sms/SmsService.java
- api/src/main/java/kr/co/pawpaw/api/controller/auth/AuthController.java
- api/src/main/java/kr/co/pawpaw/api/dto/pet/CreatePetRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/position/PositionRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/position/PositionResponse.java
- api/src/main/java/kr/co/pawpaw/api/dto/sms/CheckVerificationCodeRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/sms/SendVerificationCodeRequest.java
- api/src/test/java/kr/co/pawpaw/api/application/sms/SmsServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/position/PositionRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/position/PositionResponseTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/sms/CheckVerificationCodeRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/sms/CheckVerificationCodeResponseTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/sms/SendVerificationCodeRequestTest.java
Fix: 회원가입 SMS 인증번호 전송 API
요청 Request 생년월일 이름 추가
- 일단 필요하다고 하셔서 요청만 수정
> Fix: 회원가입 SMS 인증번호 전송 API 요청 Request 생년월일 이름 추가

- api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
- api/src/main/java/kr/co/pawpaw/api/application/boardlike/BoardLikeService.java
- api/src/main/java/kr/co/pawpaw/api/application/reply/ReplyService.java
- api/src/main/java/kr/co/pawpaw/api/controller/board/BoardRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/boardlike/BoardLikeRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/reply/ReplyController.java
- api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
- api/src/main/java/kr/co/pawpaw/api/dto/reply/ReplyDto.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
- common/src/main/java/kr/co/pawpaw/common/exception/reply/ReplyException.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/domain/Board.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/repository/BoardRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/repository/CustomBoardRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/service/query/BoardQuery.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/board/service/query/CustomBoardRepositoryImpl.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardlike/domain/BoardLikes.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardlike/repository/BoardLikesRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardlike/service/command/BoardLikeCommand.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardlike/service/query/BoardLikeQuery.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/domain/Reply.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/repository/CustomReplyRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/repository/ReplyRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/service/command/ReplyCommand.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/service/query/CustomReplyRepositoryImpl.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/reply/service/query/ReplyQuery.java
1. 댓글과 대댓글 관련 기능 추가
2. 무한스크롤 페이징으로 게시글 조회 기능 추가
3. 댓글과 관련된 예외처리 코드 추가
4. BoardLike 패키지 생성 및 이동
> 댓글, 대댓글 CRUD, 게시글 리스트 조회, BoardLike 관련 클래스 패키지 이동

- api/src/main/java/kr/co/pawpaw/api/application/board/BoardService.java
- api/src/main/java/kr/co/pawpaw/api/application/boardImg/BoardImgService.java
- api/src/main/java/kr/co/pawpaw/api/controller/boardImg/BoardImgRestController.java
- api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
- api/src/main/java/kr/co/pawpaw/api/dto/boardImg/BoardImgDto.java
- common/src/main/java/kr/co/pawpaw/common/exception/board/BoardImgException.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardImg/domain/BoardImg.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardImg/repository/BoardImgRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardImg/service/command/BoardImgCommand.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/boardImg/service/query/BoardImgQuery.java
1. 게시글 이미지 업로드 기능 구현
2. 이미지 조회 기능 구현
3. 이미지 삭제 기능 구현
> [feat] 게시글 이미지 업로드, 조회, 삭제 기능 구현

- api/src/main/java/kr/co/pawpaw/api/service/user/UserService.java
Fix: 유저 정보 조회 api 수정 nullpointexception 수정
> Fix: 유저 정보 조회 api 수정 nullpointexception 수정

- api/src/main/java/kr/co/pawpaw/api/service/chatroom/ChatroomService.java
- api/src/test/java/kr/co/pawpaw/api/application/chatroom/ChatroomServiceTest.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/chatroom/repository/ChatroomCustomRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/chatroom/repository/TrandingChatroomRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/chatroom/service/query/TrandingChatroomQuery.java
- domain/domain-rdb/src/test/java/kr/co/pawpaw/domainrdb/chatroom/repository/ChatroomCustomRepositoryTest.java
- domain/domain-rdb/src/test/java/kr/co/pawpaw/domainrdb/chatroom/repository/TrandingChatroomRepositoryTest.java
- domain/domain-rdb/src/test/java/kr/co/pawpaw/domainrdb/chatroom/service/query/TrandingChatroomQueryTest.java
Fix: 추천하는 채팅방 랜덤 정렬로 변경
Fix: 채팅방 참여시 뜨고있는 채팅방으로 설정안되어있으면 설정함
> Fix: 추천하는 채팅방 랜덤 정렬로 변경 Fix: 채팅방 참여시 뜨고있는 채팅방으로 설정안되어있으면 설정함

- api/src/main/java/kr/co/pawpaw/api/config/auth/provider/JwtTokenProvider.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/chatroom/repository/TrandingChatroomCustomRepository.java
- domain/domain-rdb/src/main/java/kr/co/pawpaw/domainrdb/common/repository/OrderByRandom.java
Fix: 뜨고있는 채팅방 id 기준 내림차순 정렬
Fix: jwt 빠르게 만료되던 버그 수정
Feat: 랜덤 기준 정렬 추가 추가
> Fix: 뜨고있는 채팅방 id 기준 내림차순 정렬 Fix: jwt 빠르게 만료되던 버그 수정 Feat: 랜덤 기준 정렬 추가 추가

- api/build.gradle
- api/src/main/java/kr/co/pawpaw/api/config/LogbookConfig.java
- api/src/main/java/kr/co/pawpaw/api/dto/chatroom/ChatroomDetailResponse.java
- api/src/main/java/kr/co/pawpaw/api/dto/chatroom/ChatroomScheduleResponse.java
- api/src/main/java/kr/co/pawpaw/api/dto/chatroom/CreateChatroomScheduleRequest.java
- api/src/main/resources/application-log.yml
- api/src/main/resources/application.yml
- docker/ecr-login.sh
- domain/dynamodb/build.gradle
- domain/dynamodb/src/main/java/kr/co/pawpaw/dynamodb/dto/chat/ChatMessageDto.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomCoverResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomNonParticipantResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomParticipantResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomScheduleParticipantResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/TrendingChatroomResponse.java
- socket/src/main/java/kr/co/pawpaw/ws/config/SecurityConfig.java
Fix: 소켓 서버 security url 수정
Fix: 채팅방 api 예시 추가
Feat: api log 추가
> Fix: 소켓 서버 security url 수정 Fix: 채팅방 api 예시 추가 Feat: api log 추가

- api/src/main/java/kr/co/pawpaw/api/controller/chatroom/ChatroomController.java
- api/src/main/java/kr/co/pawpaw/api/service/chatroom/ChatroomService.java
- api/src/test/java/kr/co/pawpaw/api/service/chatroom/ChatroomServiceTest.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomSimpleResponse.java
> Feat: 채팅방 기본 조회 api 추가

- api/src/main/java/kr/co/pawpaw/api/controller/chatroom/ChatroomController.java
- api/src/main/java/kr/co/pawpaw/api/controller/chatroom/ChatroomScheduleController.java
- api/src/main/java/kr/co/pawpaw/api/service/chatroom/ChatroomScheduleService.java
- api/src/main/java/kr/co/pawpaw/api/service/chatroom/ChatroomService.java
- api/src/test/java/kr/co/pawpaw/api/service/chatroom/ChatroomScheduleServiceTest.java
- api/src/test/java/kr/co/pawpaw/api/service/chatroom/ChatroomServiceTest.java
- common/src/main/java/kr/co/pawpaw/common/exception/chatroom/AlreadyChatroomScheduleParticipantException.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/dto/ChatroomSimpleResponse.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/repository/ChatroomCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/repository/ChatroomScheduleParticipantRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/service/command/ChatroomScheduleParticipantCommand.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/service/query/ChatroomQuery.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/service/query/ChatroomScheduleParticipantQuery.java
Fix: 채팅방 참여 API 수정
Fix: 채팅방 정보 조회 API 수정
Fix: 채팅방 스케줄 삭제 API 버그 픽스
> Fix: 채팅방 참여 API 수정 Fix: 채팅방 정보 조회 API 수정 Fix: 채팅방 스케줄 삭제 API 버그 픽스

- api/src/main/java/kr/co/pawpaw/api/controller/board/BoardRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/boardImg/BoardImgRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/boardlike/BoardLikeRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/bookmark/BookmarkRestController.java
- api/src/main/java/kr/co/pawpaw/api/controller/reply/ReplyController.java
- api/src/main/java/kr/co/pawpaw/api/service/board/BoardService.java
- api/src/main/java/kr/co/pawpaw/api/service/reply/ReplyService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/repository/BoardRepositoryCustom.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/service/query/BoardQuery.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/service/query/BoardRepositoryCustomImpl.java
1. 마이페이지에서 내가 작성한 글의 목록을 조회한다.
2. 댓글 삭제시 대댓글을 같이 삭제하는 것이 아닌 해당하는 댓글만 삭제한다.
> [feat] 마이페이지에서 마이 피드 보기

- api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
- api/src/main/java/kr/co/pawpaw/api/dto/reply/ReplyDto.java
> [fix] 스웨거 코드 수정

- api/src/main/java/kr/co/pawpaw/api/config/SpringDocsConfig.java
> Feat: 운영 swagger 제거

- api/src/main/java/kr/co/pawpaw/api/config/SecurityConfig.java
- api/src/main/java/kr/co/pawpaw/api/config/SpringDocsConfig.java
> Fix: 운영 swagger 제거

- domain/dynamodb/src/main/java/kr/co/pawpaw/dynamodb/config/DynamoDBConfig.java
> HotFix: dynamodb 설정 수정

- api/src/main/java/kr/co/pawpaw/api/config/auth/filter/JwtFilter.java
- api/src/main/java/kr/co/pawpaw/api/config/auth/repository/CookieAuthorizationRequestRepository.java
- api/src/main/java/kr/co/pawpaw/api/config/auth/service/CustomUserDetailService.java
- api/src/main/java/kr/co/pawpaw/api/config/handler/GlobalExceptionHandler.java
- api/src/main/java/kr/co/pawpaw/api/controller/auth/AuthController.java
- api/src/main/java/kr/co/pawpaw/api/service/auth/SignOutService.java
- api/src/main/java/kr/co/pawpaw/api/util/cookie/CookieUtil.java
- common/src/main/java/kr/co/pawpaw/common/exception/auth/AuthenticationException.java
- common/src/main/java/kr/co/pawpaw/common/exception/common/ErrorCode.java
> Fix: 로그아웃 api 수정

- api/src/main/java/kr/co/pawpaw/api/dto/auth/SignUpRequest.java
- api/src/main/java/kr/co/pawpaw/api/dto/auth/SocialSignUpRequest.java
- api/src/test/java/kr/co/pawpaw/api/dto/auth/SignUpRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/dto/auth/SocialSignUpRequestTest.java
- api/src/test/java/kr/co/pawpaw/api/util/CookieUtilTest.java
> Fix: 회원가입 한줄소개 추가

- api/src/main/java/kr/co/pawpaw/api/controller/board/BoardRestController.java
- api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
- api/src/main/java/kr/co/pawpaw/api/dto/reply/ReplyDto.java
- api/src/main/java/kr/co/pawpaw/api/service/board/BoardService.java
- api/src/main/java/kr/co/pawpaw/api/service/bookmark/BookmarkService.java
- api/src/main/java/kr/co/pawpaw/api/service/reply/ReplyService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/domain/Board.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/repository/BoardRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/service/query/BoardQuery.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/bookmark/repository/BookmarkCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/bookmark/repository/BookmarkRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/bookmark/service/query/BookmarkQuery.java
1. 이미지 업로드 및 조회 코드수정
2. 북마크 등록과 조회 코드 수정
3. nullException 처리
4. 댓글의 등록날짜와 수정날짜 추가
> [fix] 이미지 업로드 및 조회 코드, 북마크 등록과 조회 코드 수정, nullException 처리

- api/src/main/java/kr/co/pawpaw/api/controller/chatroom/ChatroomController.java
- api/src/main/java/kr/co/pawpaw/api/service/chatroom/ChatroomService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/repository/ChatroomCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/service/query/ChatroomQuery.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/common/repository/CustomDialect.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/chatroom/repository/ChatroomCustomRepositoryTest.java
> Fix: 채팅방 검색 paging 적용되도록 수정

- api/src/main/java/kr/co/pawpaw/api/dto/board/BoardDto.java
- api/src/main/java/kr/co/pawpaw/api/service/board/BoardService.java
- api/src/main/java/kr/co/pawpaw/api/service/boardlike/BoardLikeService.java
- api/src/main/java/kr/co/pawpaw/api/service/bookmark/BookmarkService.java
- api/src/main/java/kr/co/pawpaw/api/service/report/ReportService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/board/domain/Board.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/boardlike/repository/BoardLikesRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/boardlike/service/query/BoardLikeQuery.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/report/repository/ReportRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/report/service/query/ReportQuery.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/board/domain/BoardTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/board/service/command/BoardCommandTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/board/service/query/BoardQueryTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/boardlike/service/command/BoardLikeCommandTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/boardlike/service/query/BoardLikeQueryTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/reply/domain/ReplyTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/reply/service/command/ReplyCommandTest.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/reply/service/query/ReplyQueryTest.java
도메인, Command, Query 클래스의 테스트 코드 작성
> [fix] updateFileUrl 메서드의 코드 수정, 도메인, Command, Query 클래스의 테스트 코드 작성

- domain/mysql/src/main/java/kr/co/pawpaw/mysql/chatroom/repository/ChatroomScheduleCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/repository/PlaceCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/repository/PlaceReviewCustomRepository.java
- domain/mysql/src/main/resources/application-rdb.yml
Fix: queryDsl transform 메서드 HikariPool connection leak 수정
> Fix: queryDsl transform 메서드 HikariPool connection leak 수정

- api/src/main/java/kr/co/pawpaw/api/controller/place/PlaceController.java
- api/src/main/java/kr/co/pawpaw/api/service/place/PlaceService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/repository/PlaceCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/service/query/PlaceQuery.java
> Fix: 장소 단일 조회 api 구현

- api/src/main/java/kr/co/pawpaw/api/service/place/PlaceService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/repository/PlaceReviewCustomRepository.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/service/query/PlaceReviewQuery.java
- domain/mysql/src/test/java/kr/co/pawpaw/mysql/place/repository/PlaceReviewCustomRepositoryTest.java
Fix: 내 장소 리뷰 조회 작성하지 않은 리뷰면 404 에러 띄우도록 수정
Fix: 장소리뷰 조회 최신 순으로 조회되도록 변경
> Fix: 내 장소 리뷰 조회 작성하지 않은 리뷰면 404 에러 띄우도록 수정 Fix: 장소리뷰 조회 최신 순으로 조회되도록 변경

- api/src/main/java/kr/co/pawpaw/api/service/place/PlaceService.java
- domain/mysql/src/main/java/kr/co/pawpaw/mysql/place/enums/PlaceTag.java
> Fix: 장소 조회 오류 수정
